
#application:
#  security:
#    jwt:
#      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
#      expiration: 86400000 # a day
#      refresh-token:
#        expiration: 604800000 # 7 days
inventory-service:
  url: http://localhost:9003
user-service:
  url: http://localhost:9002
book-service:
  url: http://localhost:9001
openapi:
  service:
    title: borrow-service doc # title that you will want to display in the Swagger UI
    version: 1.0.0
    url: http://localhost:9004
springdoc:
  api-docs:
    path: /borrow/v3/api-docs
  swagger-ui:
    path: /borrow/swagger-ui.html